### ISSUE TITLE
Carthage platform iOS?

### ISSUE THREAD

**Issue by JonasSailer** [mentrena/SyncKit#68] opened 2018-11-12 15:15 UTC
We're using SyncKit with our app that has lots of other dependencies. The other dependencies only work with _carthage update --platform iOS . 
I'm getting build errors when trying the same with SyncKit. Right now we're extracting the SyncKit Framework from the sample project, since header files are missing for realm when trying usual carthage update. 
We're using it for iOS only with CoreData.

**Comment by mentrena** [comment] 2018-12-01 18:01
Hi @JonasSailer ,

Just to confirm, is the problem that when you run `carthage update` the project gets cloned and built without errors, but the framework in `Carthage/Build/iOS` is not the one you want?

**Comment by JonasSailer** [comment] 2018-12-03 10:49
I get problems while building: 
*** Skipped building xcconfigs due to the error:
Dependency "xcconfigs" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/jspahrsummers/xcconfigs/issues/new

When i skip SyncKit it works fine without errors.
I added the following line to my cartfile: 
github "mentrena/SyncKit" ~> 0.6.7

**Comment by mentrena** [comment] 2018-12-03 11:03
Out of curiosity, what happens if you remove everything else and leave only SyncKit in your Cartfile?
Would you be able to share the Cartfile?

**Comment by mentrena** [comment] 2018-12-03 13:31
Yes, that problem I am aware of :)
The problem is that there's six shared schemes (CoreData iOS/Mac, Realm iOS/Mac, RealmSwift iOS/Mac), and they all produce a framework called SyncKit.framework. Carthage doesn't allow specifying subspecs or anything like that, so it just builds all six of them and preserves only the last one, which happens to be just Realm in this case.
Will probably rename the frameworks to something like SyncKitCoreDataiOS...

**Comment by mentrena** [comment] 2019-07-06 20:12
This should be fixed in 0.7.2

**Closed by mentrena** 2019-07-06 20:12 UTC
