### ISSUE TITLE
circular reference : upload large amount of data failed (but download ok)

### ISSUE THREAD

**Issue by LeJeko** [mentrena/SyncKit#70] opened 2018-11-26 17:03 UTC
I have a data model with circular references like this:
<img width="528" alt="image" src="https://user-images.githubusercontent.com/13176530/49025575-4931e900-f19c-11e8-8216-a0f886b71fe1.png">

SyncKit is working fine with this model, except when I try to sync (upload) more than 100 records to CloudKit at the same time. It is not a issue when the games and scores are created and synced as you go, but it fail with an imported group with large amount of data.
I know I can increase the limit near 400 but no more...

Which is weird, when I sync the same huge group (created ans synced as you go) from CloudKit to another empty device all is working fine! (502 records in my case).

Can you tell me if is it an issue with SyncKit implementation or the cause of different behavior of CloudKit when downloading or uploading data ?

**Comment by mentrena** [comment] 2018-11-28 13:05
Hmm just based on that I can't spot the cause of your problem, would you have a sample project you can share?

**Comment by LeJeko** [comment] 2018-11-29 10:17
Sorry, I forgot to mention that the error is CKErrorPartialFailure -> parent of a record to save isn't on the server.
After investigations, I can explain more:
When you handle the CKLimitExceeded, you split of recordsToSave and generate a new CKModifyRecordsOperation. This behavior break the need to have all records in the same CKModifyRecordsOperation when records have CKReferences for CloudKit to be able to map them.

Here is another good explanation of the issue: https://github.com/ProcedureKit/ProcedureKit/pull/294#issuecomment-220839793

This other comment refers to Seam3 can be helpful too:
https://stackoverflow.com/questions/42465192/ckmodifyrecordsoperation-not-working-for-complete-batch-of-records#comment72088146_42465192

All confirmed in this transcript of a WWDC2015 session (search CKErrorPartialFailure):
https://asciiwwdc.com/2015/sessions/715

**Comment by mentrena** [comment] 2018-11-29 16:53
Ah that error message really sheds light on the issue, thanks :)
Ok, I think I have an idea how to fix it.
Just out of curiosity, how are you going to model the parent property for XcScore in your model?

**Comment by mentrena** [comment] 2018-11-30 14:50
I was wondering about the `parent` property, but I imagine it's XcGame? Just asking because a score has to-one properties pointing to both game and player, but when it comes to modeling your data tree for CloudKit you would have to choose one entity or the other as the parent for XcScore.

The idea would be to ensure that any batch that gets uploaded to CloudKit includes the CKRecord for any CKReference that appears as a parent in that batch (if the parent hasn't already been uploaded). It would mean that for a batch size of `n` the library might potentially try to upload `n + h` items, where `h` is the height of your model tree, but I guess that's negligible compared to the library just not being able to sync.

**Comment by LeJeko** [comment] 2018-12-01 00:18
Sort answer, I let SyncKit doing the job for me ;-)
Seriously, in my case, the first step is to create a XcGroup with its XcPlayers. Next steps create a XcGame with XcSores associated as I explained. So, if sync are made as you go, the parent for XcSore will always be XcGame in CloudKit.

Thank you for sharing. After a long reflexion about your idea, I think it's possible without the need to know the model tree:
I consider the general case of a first sync of my model to CloudKit with a lot of changes tracked by SyncKit. So there can be several groups too.
Instead of sorting the CKRecord, consider doing that with the CoreData objects to be synchronized.
If you implement a logic that ensure that all "to-one" relationships of an object are present before it (or already on the server), logically all generated CKRecord will be automatically sorted.
If I take my case, the logic should sort the records as: XcGroup -> XcPlayer -> XcGame -> XcScore
In this case, a split of the batch should no longer generate an error.

However, CloudKit operations remain asynchronous and could still cause problems. (-> CKOperationGroup?)

**Comment by mentrena** [comment] 2018-12-01 15:15
> If you implement a logic that ensure that all "to-one" relationships of an object are present before it (or already on the server)

It sounds like the problem only happens for "parent" records though. The parent record is determined by your implementation of  ```static func parentKey() -> String```
Other to-one relationships seem to be fine.

Anyway, hope to have a fix relatively soon 👍

**Comment by mentrena** [comment] 2018-12-01 17:33
I have pushed this branch: https://github.com/mentrena/SyncKit/tree/fix/parentBatch
Could you please give it a try and let me know? You can use this in your Podfile to check it out.
```
pod 'SyncKit', :git => 'https://github.com/mentrena/SyncKit.git', :branch => 'fix/parentBatch'
```

**Comment by mentrena** [comment] 2018-12-03 09:53
Thanks, just pushed an update that I hope will fix that.

**Comment by LeJeko** [comment] 2018-12-03 11:48
Great, it works! Thank you 🥇

**Comment by mentrena** [comment] 2018-12-03 13:32
Awesome, I'll add the same fix for Realm/RealmSwift and release it. Thanks!

**Comment by LeJeko** [comment] 2018-12-03 15:44
Just before closing, now it can sync a huge amount of data and can take a long time to complete.
I've try to increase the `QSDefaultBatchSize` to 200 or 400 and it seems to me that's a little bit faster.
Can you confirm it?

**Comment by mentrena** [comment] 2018-12-03 16:42
Any idea how much faster? I haven't actually measured times, can't remember how I landed on 100 as the default size.

**Comment by LeJeko** [comment] 2018-12-03 23:46
I did some quick measurements using `print(Date())` and there is only about 1 second difference.

I think it's just because there are more connections with 100 than 400.

When `QSDefaultBatchSize = 100`, the batch is separated as follows:
_100, 101, 100, 100, 100, 93_ => complete task in 28-33 sec
With `QSDefaultBatchSize = 400`:
_400, 194_ => complete task in 26-32 sec
With `QSDefaultBatchSize = 500`:
_250, 251, 93_ => not measured

As you know, the` CKErrorLimitExceeded` is actually 400 but can change at any time depends on CloudKit load. You have probably chosen 100 to be sure of not reaching the limit.

**Comment by mentrena** [comment] 2018-12-04 09:31
Cool, thanks for the info!
For the next release I've made it 200 by default and made `batchSize` writable so you can change it too 👍

**Comment by LeJeko** [comment] 2018-12-04 09:39
Perfect 👍

**Comment by mentrena** [comment] 2018-12-06 10:20
Published `0.6.11`, thanks!

**Closed by mentrena** 2018-12-06 10:20 UTC

**Comment by LeJeko** [comment] 2018-12-06 11:07
Just for information, I had to use:
`pod 'SyncKit/CoreData', :git => 'https://github.com/mentrena/SyncKit.git'` to retrieve 0.6.11,
`pod 'SyncKit/CoreData'` always retrieve 0.6.10 ???

**Comment by mentrena** [comment] 2018-12-06 20:53
It was probably CocoaPods not having fully updated, it seems to work now.
