### ISSUE TITLE
Fatal Error in recordToUpload method

### ISSUE THREAD

**Issue by dstranz** [mentrena/SyncKit#106] opened 2019-11-07 10:03 UTC
We are experiencing a crash in recordToUpload method when originalObject is nil.

![Zrzut ekranu 2019-11-7 o 10 23 58](https://user-images.githubusercontent.com/96502/68379591-7463dd00-014e-11ea-82e0-065166a7e310.png)

I'm not sure if such record should be totally ignored during sync or deleted from iCloud?

**Comment by mentrena** [comment] 2019-11-07 11:34
It probably should be ignored, but I'd like to understand why this happens.
By any chance do you know how easy to reproduce this is? Was the object deleted halfway through a sync?

**Comment by dstranz** [comment] 2019-11-07 12:13
I'm trying to reproduce it on my device, but yes, it was related to sam remove / insert CD opbejcts flow.

**Comment by dstranz** [comment] 2019-11-07 12:30
OK, I'm able to reproduce it. I have 2 Core Data entities A and B with relation A(1) to B(N).

1. I have object A with (let's say) uniqueId=A1 and B with uniqueId=B1.
2. Then I'm removing B1
3. ...and adding new object with uniqueId=B1 and related to A1

When I'm doing that several times and restart app CloudKit crashes.

**Comment by mentrena** [comment] 2019-11-07 12:35
Is that happening halfway through the synchronisation?

**Comment by dstranz** [comment] 2019-11-07 12:37
It's crashing when I'm calling `synchronize()` in AppDelegate during launch.

**Comment by mentrena** [comment] 2019-11-07 12:47
Ok, my first instinct would be to recommend using fully unique identifiers, since B1 and B1' are not really the same object. You could use UDIDs and still keep a property with your own different identifier, so even if they're different objects to CloudKit they can still be considered the same by your app.

**Comment by dstranz** [comment] 2019-11-07 13:48
@mentrena Yes, after further tests it's definitely related to reusing the same uniqueId.

**Comment by mentrena** [comment] 2019-11-12 19:50
Cool, I'm closing the issue, feel free to reopen or get in touch if you have more questions about this.

**Closed by mentrena** 2019-11-12 19:50 UTC
